views:
  rds_analysis_dist_view:    # Change from array to dictionary format
    query: |
        CREATE OR REPLACE VIEW "${data_collection_database_name}"."rds_analysis_dist_view" AS 
        SELECT
          rds_analysis_data.dbinstanceidentifier
        , rds_analysis_data.dbinstanceclass
        , rds_analysis_data.engine
        , rds_analysis_data.dbinstancestatus
        , rds_analysis_data.masterusername
        , rds_analysis_data.endpoint
        , rds_analysis_data.allocatedstorage
        , rds_analysis_data.instancecreatetime
        , rds_analysis_data.preferredbackupwindow
        , rds_analysis_data.backupretentionperiod
        , rds_analysis_data.dbsecuritygroups
        , rds_analysis_data.vpcsecuritygroups
        , rds_analysis_data.dbparametergroups
        , rds_analysis_data.availabilityzone
        , rds_analysis_data.dbsubnetgroup
        , rds_analysis_data.preferredmaintenancewindow
        , rds_analysis_data.latestrestorabletime
        , rds_analysis_data.multiaz
        , rds_analysis_data.engineversion
        , rds_analysis_data.autominorversionupgrade
        , rds_analysis_data.readreplicadbinstanceidentifiers
        , rds_analysis_data.licensemodel
        , rds_analysis_data.optiongroupmemberships
        , rds_analysis_data.publiclyaccessible
        , rds_analysis_data.storagetype
        , rds_analysis_data.dbinstanceport
        , rds_analysis_data.storageencrypted
        , rds_analysis_data.dbiresourceid
        , rds_analysis_data.cacertificateidentifier
        , rds_analysis_data.domainmemberships
        , rds_analysis_data.copytagstosnapshot
        , rds_analysis_data.monitoringinterval
        , rds_analysis_data.dbinstancearn
        , rds_analysis_data.iamdatabaseauthenticationenabled
        , rds_analysis_data.performanceinsightsenabled
        , rds_analysis_data.performanceinsightskmskeyid
        , rds_analysis_data.performanceinsightsretentionperiod
        , rds_analysis_data.deletionprotection
        , rds_analysis_data.associatedroles
        , rds_analysis_data.maxallocatedstorage
        , rds_analysis_data.activitystreamstatus
        , rds_analysis_data.backuptarget
        , rds_analysis_data.networktype
        , rds_analysis_data.storagethroughput
        , rds_analysis_data.certificatedetails
        , rds_analysis_data.dedicatedlogvolume
        , rds_analysis_data.accountid
        , organization_data.name "accountname"
        , rds_analysis_data.collection_date
        , rds_analysis_data.region
        , rds_analysis_data.current_major_version
        , rds_analysis_data.latest_major_version
        , rds_analysis_data."latest_major_version_n-1" "latest_major_version_N-1"
        , rds_analysis_data."latest_major_version_n-2" "latest_major_version_N-2"
        , rds_analysis_data.current_minor_version
        , rds_analysis_data.latest_minor_version
        , rds_analysis_data."latest_minor_version_n-1" "latest_minor_version_N-1"
        , rds_analysis_data."latest_minor_version_n-2" "latest_minor_version_N-2"
        , rds_analysis_data.dbname
        , rds_analysis_data.kmskeyid
        , rds_analysis_data.enginelifecyclesupport
        , rds_analysis_data.dbclusteridentifier
        , rds_analysis_data.engine_version_status
        , rds_analysis_data.readreplicasourcedbinstanceidentifier
        , array_join(transform(rds_analysis_data.taglist, (x) -> concat(x.Key, ':', x.Value)), ', ') taglist
        , rds_maintenance_data.action
        , rds_maintenance_data.description
        , rds_maintenance_data.currentapplydate
        , rds_maintenance_data.autoappliedafterdate
        , rds_maintenance_data.forcedapplydate
        , rds_maintenance_data.optinstatus
        , rds_analysis_data.payer_id
        , rds_analysis_data.year
        , rds_analysis_data.month
        , rds_analysis_data.day
        FROM
          ((rds_analysis_data
        LEFT JOIN organization_data ON (rds_analysis_data.accountid = organization_data.id))
        LEFT JOIN rds_maintenance_data ON ((rds_maintenance_data.resourceidentifier = rds_analysis_data.dbinstancearn) 
        AND (rds_maintenance_data.accountid = rds_analysis_data.accountid) 
        AND (date(CAST(rds_maintenance_data.collection_date AS timestamp)) = date(CAST(rds_analysis_data.collection_date AS timestamp))) 
        AND (rds_maintenance_data.region = rds_analysis_data.region) 
        AND (rds_maintenance_data.payer_id = rds_analysis_data.payer_id)))

datasets:
  rds_analysis_dist_view:
    data:
      DataSetId: "rds-analysis-dataset-001"
      Name: rds_analysis_dist_view
      PhysicalTableMap:
        "rds-analysis-table-001":
          RelationalTable:
            DataSourceArn: ${athena_datasource_arn}
            Catalog: ${glue_data_catalog}
            Schema: ${data_collection_database_name}
            Name: rds_analysis_dist_view
            InputColumns:
              - Name: dbinstanceidentifier
                Type: STRING
              - Name: dbinstanceclass
                Type: STRING
              - Name: engine
                Type: STRING
              - Name: dbinstancestatus
                Type: STRING
              - Name: masterusername
                Type: STRING
              - Name: endpoint
                Type: STRING
              - Name: allocatedstorage
                Type: INTEGER
              - Name: instancecreatetime
                Type: DATETIME
              - Name: preferredbackupwindow
                Type: STRING
              - Name: backupretentionperiod
                Type: INTEGER
              - Name: dbsecuritygroups
                Type: STRING
              - Name: vpcsecuritygroups
                Type: STRING
              - Name: dbparametergroups
                Type: STRING
              - Name: availabilityzone
                Type: STRING
              - Name: dbsubnetgroup
                Type: STRING
              - Name: preferredmaintenancewindow
                Type: STRING
              - Name: latestrestorabletime
                Type: DATETIME
              - Name: multiaz
                Type: BOOLEAN
              - Name: engineversion
                Type: STRING
              - Name: autominorversionupgrade
                Type: BOOLEAN
              - Name: readreplicadbinstanceidentifiers
                Type: STRING
              - Name: licensemodel
                Type: STRING
              - Name: optiongroupmemberships
                Type: STRING
              - Name: publiclyaccessible
                Type: BOOLEAN
              - Name: storagetype
                Type: STRING
              - Name: dbinstanceport
                Type: INTEGER
              - Name: storageencrypted
                Type: BOOLEAN
              - Name: dbiresourceid
                Type: STRING
              - Name: cacertificateidentifier
                Type: STRING
              - Name: domainmemberships
                Type: STRING
              - Name: copytagstosnapshot
                Type: BOOLEAN
              - Name: monitoringinterval
                Type: INTEGER
              - Name: dbinstancearn
                Type: STRING
              - Name: iamdatabaseauthenticationenabled
                Type: BOOLEAN
              - Name: performanceinsightsenabled
                Type: BOOLEAN
              - Name: performanceinsightskmskeyid
                Type: STRING
              - Name: performanceinsightsretentionperiod
                Type: INTEGER
              - Name: deletionprotection
                Type: BOOLEAN
              - Name: associatedroles
                Type: STRING
              - Name: maxallocatedstorage
                Type: INTEGER
              - Name: activitystreamstatus
                Type: STRING
              - Name: backuptarget
                Type: STRING
              - Name: networktype
                Type: STRING
              - Name: storagethroughput
                Type: INTEGER
              - Name: certificatedetails
                Type: STRING
              - Name: dedicatedlogvolume
                Type: STRING
              - Name: accountid
                Type: STRING
              - Name: accountname
                Type: STRING
              - Name: collection_date
                Type: DATETIME
              - Name: region
                Type: STRING
              - Name: current_major_version
                Type: STRING
              - Name: latest_major_version
                Type: STRING
              - Name: latest_major_version_N-1
                Type: STRING
              - Name: latest_major_version_N-2
                Type: STRING
              - Name: current_minor_version
                Type: STRING
              - Name: latest_minor_version
                Type: STRING
              - Name: latest_minor_version_N-1
                Type: STRING
              - Name: latest_minor_version_N-2
                Type: STRING
              - Name: dbname
                Type: STRING
              - Name: kmskeyid
                Type: STRING
              - Name: enginelifecyclesupport
                Type: STRING
              - Name: dbclusteridentifier
                Type: STRING
              - Name: engine_version_status
                Type: STRING
              - Name: readreplicasourcedbinstanceidentifier
                Type: STRING
              - Name: taglist
                Type: STRING
              - Name: action
                Type: STRING
              - Name: description
                Type: STRING
              - Name: currentapplydate
                Type: DATETIME
              - Name: autoappliedafterdate
                Type: DATETIME
              - Name: forcedapplydate
                Type: DATETIME
              - Name: optinstatus
                Type: STRING
              - Name: payer_id
                Type: STRING
              - Name: year
                Type: INTEGER
              - Name: month
                Type: INTEGER
              - Name: day
                Type: INTEGER
      LogicalTableMap:
        "rds-analysis-logical-001":
          Alias: rds_analysis_dist_view
          Source:
            PhysicalTableId: "rds-analysis-table-001"
      ImportMode: SPICE
    dependsOn:
      views:
        - rds_analysis_dist_view
    schedules:
      - default

dashboard:
  name: "RDS Analysis"
  id: "rds-analysis-views"
  dependsOn:
    datasets:
      - rds_analysis_dist_view
  category: "Custom"
  theme: "MIDNIGHT"
  version: "1.0.0"
  permissions:
    - principal: "*"
      actions:
        - "quicksight:DescribeDashboard"
        - "quicksight:ListDashboardVersions"